### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter '...

### ISSUE THREAD

**Issue by rhiskey** [rhiskey/vkaudioposter_Console#59]
View details in Rollbar: [https://rollbar.com/first3395/vkaudioposter_Console/items/29/](https://rollbar.com/first3395/vkaudioposter_Console/items/29/)

```
Traceback (most recent call last):
  File "System.Text.RegularExpressions.ThrowHelper", line 11, in System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(System.Text.RegularExpressions.ExceptionArgument arg)
  File "System.Text.RegularExpressions.Regex", line 3, in System.Text.RegularExpressions.Regex.IsMatch(System.String input)
  File "L:\GitHub\vkaudioposter_Console\Program.cs", line 1152, in vkaudioposter_Console.Program.PhotoParserAuto(System.String photostock, System.Int32 i, System.String music_style, System.Int32 pickedStockPage)
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
```

**Comment by rhiskey** [comment]
Don't try to PhotoParserAuto when null queue and null photourl, don't try catch if load playlist image
